import 'package:flutter/material.dart';
import './blinker.dart';
import './resultscreen.dart';
import 'package:flutter/cupertino.dart';

class MainScreen extends StatefulWidget {
  @override
  _MainScreenState createState() => _MainScreenState();
}

class _MainScreenState extends State<MainScreen> {
  static List countryNames = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Congo (Brazzaville)',
    'Congo (Kinshasa)',
    'Costa Rica',
    "Cote d'Ivoire",
    'Croatia',
    'Diamond Princess',
    'Cuba',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Djibouti',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Guatemala',
    'Guinea',
    'Guyana',
    'Haiti',
    'Holy See',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'South Korea',
    'Kuwait',
    'Kyrgyzstan',
    'Latvia',
    'Lebanon',
    'Liberia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malaysia',
    'Maldives',
    'Malta',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Namibia',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'San Marino',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Somalia',
    'South Africa',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Taiwan*',
    'Tanzania',
    'Thailand',
    'Togo',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'Uruguay',
    'US',
    'Uzbekistan',
    'Venezuela',
    'Vietnam',
    'Zambia',
    'Zimbabwe',
    'Dominica',
    'Grenada',
    'Mozambique',
    'Syria',
    'Timor-Leste',
    'Belize',
    'Laos',
    'Libya',
    'West Bank and Gaza',
    'Guinea-Bissau',
    'Mali',
    'Saint Kitts and Nevis',
    'Kosovo',
    'Burma',
    'MS Zaandam',
    'Botswana',
    'Burundi',
    'Sierra Leone',
    'Malawi',
    'South Sudan',
    'Western Sahara',
    'Sao Tome and Principe'
  ];
  List countryFlag = [
    'AF',
    'AL',
    'DZ',
    'AD',
    'AO',
    'AG',
    'AR',
    'AM',
    'AU',
    'AT',
    'AZ',
    'BS',
    'BH',
    'BD',
    'BB',
    'BY',
    'BE',
    'BJ',
    'BT',
    'BO',
    'BA',
    'BR',
    'BN',
    'BG',
    'BF',
    'CV',
    'KH',
    'CM',
    'CA',
    'CF',
    'TD',
    'CL',
    'CN',
    'CO',
    'CD',
    'CG',
    'CR',
    'CI',
    'HR',
    '',
    'CU',
    'CY',
    'CZ',
    'DK',
    'DJ',
    'DO',
    'EC',
    'EG',
    'SV',
    'GQ',
    'ER',
    'EE',
    '',
    'ET',
    'FJ',
    'FI',
    'FR',
    'GA',
    'GM',
    'GE',
    'DE',
    'GH',
    'GR',
    'GT',
    'GN',
    'GY',
    'HT',
    'VA',
    'HN',
    'HU',
    'IS',
    'IN',
    'ID',
    'IR',
    'IQ',
    'IE',
    'IL',
    'IT',
    'JM',
    'JP',
    'JO',
    'KZ',
    'KE',
    'KR',
    'KW',
    'KG',
    'LV',
    'LB',
    'LR',
    'LI',
    'LT',
    'LU',
    'MG',
    'MY',
    'MV',
    'MT',
    'MR',
    'MU',
    'MX',
    'MD',
    'MC',
    'MN',
    'ME',
    'MA',
    'NA',
    'NP',
    'NL',
    'NZ',
    'NI',
    'NE',
    'NG',
    'MK',
    'NO',
    'OM',
    'PK',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'QA',
    'RO',
    'RU',
    'RW',
    'LC',
    'VC',
    'SM',
    'SA',
    'SN',
    'RS',
    'SC',
    'SG',
    'SK',
    'SI',
    'SO',
    'ZA',
    'ES',
    'LK',
    'SD',
    'SR',
    'SE',
    'CH',
    'TW',
    'TZ',
    'TH',
    'TG',
    'TT',
    'TN',
    'TR',
    'UG',
    'UA',
    'AE',
    'GB',
    'UY',
    'US',
    'UZ',
    'VE',
    'VN',
    'ZM',
    'ZW',
    'DM',
    'GD',
    'MZ',
    'SY',
    'TL',
    'BZ',
    'LA',
    'LY',
    '',
    'GW',
    'ML',
    'KN',
    'XK',
    '',
    '',
    'BW',
    'BI',
    'SL',
    'MW',
    'SS',
    'EH',
    'ST'
  ];
  final duplicateItems =
      List<String>.generate(countryNames.length, (i) => countryNames[i]);
  TextEditingController editingController = TextEditingController();
  var items = List<String>();
  void filterSearchResults(String query) {
    List<String> dummySearchList = List<String>();
    dummySearchList.addAll(duplicateItems);
    if (query.isNotEmpty) {
      List<String> dummyListData = List<String>();
      dummySearchList.forEach((item) {
        if (item.contains(query)) {
          dummyListData.add(item);
        }
      });
      setState(() {
        items.clear();
        items.addAll(dummyListData);
      });
      return;
    } else {
      setState(() {
        items.clear();
        items.addAll(duplicateItems);
      });
    }
  }

  @override
  void initState() {
    items.addAll(duplicateItems);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Container(
        decoration: BoxDecoration(
          color: Color.fromARGB(255, 247, 247, 247),
        ),
        child: Column(
          children: <Widget>[
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: TextField(
                textCapitalization: TextCapitalization.sentences,
                onChanged: (value) {
                  filterSearchResults(value);
                },
                controller: editingController,
                decoration: InputDecoration(
                    labelText: "Search",
                    hintText: "Select Country",
                    prefixIcon: Icon(Icons.search),
                    border: OutlineInputBorder(
                        borderRadius: BorderRadius.all(Radius.circular(25.0)))),
              ),
            ),
            Expanded(
              flex: 15,
              child: Container(
                child: ListView.builder(
                    itemCount: items.length,
                    // separatorBuilder: (context, index) {
                    //   return Divider(
                    //     height: 1,
                    //     thickness: 1,
                    //     color: Color.fromARGB(255, 255, 97, 115),
                    //   );
                    // },
                    itemBuilder: (context, index) {
                      return SizedBox(
                        height: 60,
                        child: Hero(
                          tag: "${items[index]}",
                          child: ListTile(
                            leading: countryFlag[index] == ''
                                ? Image.asset(
                                    "assets/icon/earth.png",
                                    width: 32,
                                  )
                                : Image.network(
                                    "https://www.countryflags.io/${countryFlag[countryNames.indexOf(items[index])]}/flat/32.png"),
                            title: Text(
                              items[index],
                              style: TextStyle(
                                  fontSize: 24,
                                  color: Color.fromARGB(
                                    255,
                                    40,
                                    40,
                                    40,
                                  )),
                            ),
                            // child:MaterialButton(
                            //   child: Padding(
                            //     padding:
                            //         const EdgeInsets.only(left: 20, top: 5),
                            //     child: Row(
                            //       children: <Widget>[
                            //         countryFlag[index] == ''
                            //             ? Container()
                            //             : Image.network(
                            //                 "https://www.countryflags.io/${countryFlag[index]}/flat/32.png"),
                            //         Text(
                            //           countryNames[index],
                            //           style: TextStyle(
                            //               fontSize: 24,
                            //               color: Color.fromARGB(
                            //                 255,
                            //                 40,
                            //                 40,
                            //                 40,
                            //               )),
                            //         ),
                            //       ],
                            //     ),
                            //   ),
                            onTap: () {
                              setState(() {
                                Navigator.push(context,
                                    CupertinoPageRoute(builder: (context) {
                                  return ResultPage(items[index]);
                                }));
                              });
                            },
                            // ),
                          ),
                        ),
                      );
                    }),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
